name: Set Helm Parameter
inputs:
  values_files:
    description: >-
      The path to the `values.yaml` file that you want to modify.
    required: true
    default: chart/values.yaml

  tag_keys:
    description: >-
      The dot-notation path to the YAML key (or keys, if listed as a CSV) that
      should be updated.
    required: true
    default: .image.tag

  tag_value:
    description: The destination tag (the new tag) to create and publish
    required: true

  bump_level:
    description: >-
      `patch`, `minor`, `major`, or `null` to skip bumping the Chart version.
    required: true
    default: patch

  helm_docs:
    description: >-
      Enables or disables (`true` or `false`) automated updating of the Helm
      documentation.
    required: true
    default: 'true'

  commit_branch:
    description: >-
      If supplied, the job will check out this branch before making any git
      commits. This is useful when you are running this action on a Tag
      trigger rather than a branch or pull-request trigger.
    required: false

  commit_tag:
    description: >-
      If supplied, the job will create a new branch pointing to the commit that
      has just been created as part of the release process. If you do not set
      $commit_branch, you must set $commit_tag or the final `git push` will
      fail.
    required: false

  commit_message:
    description: Commit message
    required: false
    default: Automated commit on behalf-of ${{ github.actor }}

  commit_and_push:
    description: Whether to commit and push to remote.
    required: true
    default: true

  force:
    description: >-
      If true, then the git tag event (and the git push) will be forced. This
      will overwrite existing tags.
    default: true
    required: true

  commit_options:
    description: Commit options (eg. --no-verify)
    required: false
    default: ''

  verbose:
    description: >-
      If set to 'true', then the 'set -x' flag will be turned on to help debug
      the action.
    required: false
    default: 'false'

  dry:
    description: >-
      If set to 'true', then at the end of the work a Git diff will be printed
      out, but no git push will happen.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7
    - name: Install dependencies
      shell: bash
      run: |
        pip install pybump yamale yamllint pyyaml
    - name: Helm set parameter
      env:
        INPUT_VALUES_FILES: ${{ inputs.values_files }}
        INPUT_TAG_KEYS: ${{ inputs.tag_keys }}
        INPUT_TAG_VALUE: ${{ inputs.tag_value }}
        INPUT_BUMP_LEVEL: ${{ inputs.bump_level }}
        INPUT_HELM_DOCS: ${{ inputs.helm_docs }}
        INPUT_COMMIT_BRANCH: ${{ inputs.commit_branch }}
        INPUT_COMMIT_TAG: ${{ inputs.commit_tag }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUT_COMMIT_AND_PUSH: ${{ inputs.commit_and_push }}
        INPUT_FORCE: ${{ inputs.force }}
        INPUT_COMMIT_OPTIONS: ${{ inputs.commit_options }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_DRY: ${{ inputs.dry }}
      shell: bash
      run: |
        helm-set-parameter.sh
